/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.viveregistro2.viveregistro.view;

/**
 *
 * @author yeison
 */
public class MenusFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenusFrame
     */
    public MenusFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblNosotros = new javax.swing.JLabel();
        lblGaleria = new javax.swing.JLabel();
        pnl1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        btnMenu2 = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(204, 204, 204));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Vive");
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Registro");
        pnlMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWelcome.setText("Welcome");
        lblWelcome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 51)));
        lblWelcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWelcomeMouseClicked(evt);
            }
        });
        pnlMenu.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 30));

        lblNosotros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNosotros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNosotros.setText("Nosotros");
        lblNosotros.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 51)));
        lblNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNosotrosMouseClicked(evt);
            }
        });
        pnlMenu.add(lblNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 30));

        lblGaleria.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGaleria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGaleria.setText("Galería");
        lblGaleria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 51)));
        lblGaleria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGaleriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGaleriaMouseEntered(evt);
            }
        });
        pnlMenu.add(lblGaleria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 30));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/icono.png"))); // NOI18N
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnl1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Vive");
        pnl1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 99, 69));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Registro");
        pnl1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 140, 40));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("\"Vive el registro, no solo el momento\"");
        pnl1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 435, 45));

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnl1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto10.jpg"))); // NOI18N
        pnl1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 680, 500));

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/icono.png"))); // NOI18N
        btnMenu1.setContentAreaFilled(false);
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        pnl2.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        btnSalir1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalir1.setText("X");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        pnl2.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NUESTRO PLANETA");
        pnl2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CUIDEMOS");
        pnl2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 110, -1));

        jLabel21.setBackground(new java.awt.Color(0, 102, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto9.jpg"))); // NOI18N
        pnl2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 150, 100));

        jLabel20.setBackground(new java.awt.Color(0, 102, 102));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto8.jpg"))); // NOI18N
        pnl2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 150, 100));

        jLabel19.setBackground(new java.awt.Color(0, 102, 102));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto7.jpg"))); // NOI18N
        pnl2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 150, 100));

        jLabel18.setBackground(new java.awt.Color(0, 102, 102));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto6.jpg"))); // NOI18N
        pnl2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 150, 100));

        jLabel17.setBackground(new java.awt.Color(0, 102, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto5.jpg"))); // NOI18N
        pnl2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 150, 100));

        jLabel16.setBackground(new java.awt.Color(0, 102, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto4.jpg"))); // NOI18N
        pnl2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 100));

        jLabel15.setBackground(new java.awt.Color(0, 102, 102));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto3.jpg"))); // NOI18N
        pnl2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 150, 100));

        jLabel14.setBackground(new java.awt.Color(0, 102, 102));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/foto2.jpg"))); // NOI18N
        pnl2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, 100));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/pexels-akil-mazumder-1072824.jpg"))); // NOI18N
        pnl2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, 100));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/pexels-flora-westbrook-1974381.jpg"))); // NOI18N
        pnl2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        getContentPane().add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, 0, 680, 500));

        pnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/viveregistro2/viveregistro/Img/icono.png"))); // NOI18N
        btnMenu2.setContentAreaFilled(false);
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });
        pnl3.add(btnMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        btnSalir2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalir2.setText("X");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        pnl3.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 40));

        jLabel24.setBackground(new java.awt.Color(0, 153, 0));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("CAMBÍO");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jLabel24.setOpaque(true);
        pnl3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 180, 180));

        jLabel22.setBackground(new java.awt.Color(0, 0, 204));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("INNOVACIÓN");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jLabel22.setOpaque(true);
        pnl3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 180));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ORGANIZACIÓN");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);
        pnl3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 180));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("<html><center>Somos un grupo que busca mejorar y condicionar el sistema del Vivero sena, el cual consiste en un sistema de riego automatizado, que aunque está bien, aun puede mejorar y ese es nuestro objetivo, mejorar.</html>");
        pnl3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 440, 100));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NOSOTROS");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnl3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 290, 80));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\yeison\\Downloads\\pexels-bongkarn-thanyakij-3787308 (1).jpg")); // NOI18N
        pnl3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        getContentPane().add(pnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-680, 0, 680, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion==0){
            Animacion.Animacion.mover_izquierda(0,-220 , 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-220,0,2, 2, pnlMenu);
            
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void lblNosotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNosotrosMouseClicked
       
        Animacion.Animacion.mover_derecha(-680,220 , 2, 2, pnl3);
        Animacion.Animacion.mover_izquierda(220,-680 , 2, 2, pnl1);
        Animacion.Animacion.mover_izquierda(220,-680 , 2, 2, pnl2);
        
        
    }//GEN-LAST:event_lblNosotrosMouseClicked

    private void lblGaleriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGaleriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGaleriaMouseEntered

    private void lblGaleriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGaleriaMouseClicked

        Animacion.Animacion.mover_derecha(-680,220 , 2, 2, pnl2);
        Animacion.Animacion.mover_izquierda(220,-680 , 2, 2, pnl1);
        Animacion.Animacion.mover_izquierda(220,-680 , 2, 2, pnl3);
        
    }//GEN-LAST:event_lblGaleriaMouseClicked

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion==0){
            Animacion.Animacion.mover_izquierda(0,-220 , 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-220,0,2, 2, pnlMenu);
            
        }
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void lblWelcomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWelcomeMouseClicked
        Animacion.Animacion.mover_derecha(-680,220 , 2, 2, pnl1);
        Animacion.Animacion.mover_izquierda(220,-680 , 2, 2, pnl2);
        Animacion.Animacion.mover_izquierda(220,-680 , 2, 2, pnl3);
        
    }//GEN-LAST:event_lblWelcomeMouseClicked

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion==0){
            Animacion.Animacion.mover_izquierda(0,-220 , 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-220,0,2, 2, pnlMenu);
            
        }
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenusFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblGaleria;
    private javax.swing.JLabel lblNosotros;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
